name: AutomaticOutputs

on:
  push:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '**.kibot.yaml'
      - '**kibot.yml'
  pull_request:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '**.kibot.yaml'
      - '**kibot.yml'

jobs:
  GetShortHash:
    name: "Retrieve short hash"
    run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV
  Autogen:
    name: "Outputs"
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad6_auto_full:latest

    steps:    
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
        
    - name: Get short hash for output
        run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV

    - uses: INTI-CMNB/KiBot@v2_k6
      with:
         config: config.kibot.yaml
         schema: 'LogDimmer.kicad_sch'
         board: 'LogDimmer.kicad_pcb'
    - name: upload results
      uses: actions/upload-artifact@v3
      with:
        name: AutomaticOutputs-$GITHUB_SHA_SHORT
        path: Output